### ISSUE TITLE
Regarding Session ID

### ISSUE THREAD

**Issue by Code-acious** [Alfex4936/Bard-rs#1]
Please tell a way so that I don't have to enter session id every time. "Bard-rs --session <my session cookie> every time I start a new terminal session I have to enter it. Please explain in detail.Thanks anyways your program works flawlessly, its just this issue.

**Comment by Alfex4936** [comment]
Hello! I completely understand your frustration, as I also felt the same way when using the program. That's why I added the option for users to pass a .env file! By using a .env file, you won't have to enter the session ID every time in the terminal.

To avoid entering the session ID every time, simply use the following command: (-e for env file name, -p for path of that env file)

```bash
bard-rs -e .env -p ./
```

Make sure to create a `.env` file in the same directory (as we set ./ otherwise set a different path), and it must contain the `SESSION_ID` key with your session ID as the value. For example, in your .env file:

```
SESSION_ID=your_session_id_here
```

This way, the program will read the session ID from the .env file automatically, saving you the hassle of entering it every time.

If you have any further questions or need additional assistance, feel free to let me know.

**Comment by Code-acious** [comment]
First of all thank you so much for the quick response! Unfortunately I tried this earlier It says

bard-rs -e .env -p /home/ayush/.cargo/bin
thread 'main' panicked at 'No session ID provided. Either pass it with -s or provide a .env file', /home/Ayush/.cargo/registry/src/github.com-1ecc6299db9ec823/bard-rs-1.0.7/src/main.rs:230:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Code-acious** [comment]
bard-rs --session <my_session_cookie>
I pasted that session cookie value in .env file
(SESSION_ID=Wgi_jBqLvrmvQxqe562KD9nCMMYGXdvxT97uBDyH67lilOYWizEtuTaeTuAKV1fXzhbsvg.)
Is SESSION_ID and Session_Cookie different thing?
how to get SESSION_ID?

**Comment by Alfex4936** [comment]
I apologize for the confusion. the keys being used for the `-s` value and `SESSION_ID` are identical, and they are both derived from `__Secure-1PSID`.

Assuming you've created a `.env` file in `/home/ayush/.cargo/bin` with the correct key, could you try appending a forward slash (`/`) at the end of the path? This might help in correctly identifying the file location.

Moreover, would you mind testing your application in the home directory, i.e., `~/` (which corresponds to `/home/ayush/`), immediately after opening your terminal? Please ensure the `.env` file is located in this directory as well. You can do this by running `bard-rs -e .env -p ./` in your home folder. (I tested on WSL2 ubuntu-22, and it worked)

Let me know if you continue to encounter the same error even after these modifications.

**Comment by Code-acious** [comment]
Yes I will but Currently I have some work to do I will update U in 3-4 hours

**Comment by Code-acious** [comment]
Sorry for late update,
The command bard-rs -e .env -p ./ works! yaay (As you said test it in your home directory). But yet I have to do this every time.
for example
If I run bard-rs solely then it gives me error
"bard-rs -e .env -p /home/ayush/.cargo/bin
thread 'main' panicked at 'No session ID provided. Either pass it with -s or provide a .env file', /home/Ayush/.cargo/registry/src/github.com-1ecc6299db9ec823/bard-rs-1.0.7/src/main.rs:230:10
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace"

but if i run bard-rs -e .env -p ./  (earlier this was not working for my desired directory eg: /home/user/.cargo/bin or even /home/user/.cargo/bin/ does not worked at all), now it works for me.

I think there is some linkage problem (I am naive) just like we link separate CSS file with desired HTML file in html code itself.

I found a workaround I will make bard -e .env - ./ as executable bash script for now.

There are another bard-cli tool but it seems it does not have interactive mode (It exists after every questions or query asked) yours is better and only exits on commad "!exit". Hope you will solve the problem Cheers!!!

**Comment by Alfex4936** [comment]
Thank you for helping me improve `bard-rs`!

I've updated the way the `bard-rs` tool works with the `.env` file.

Now, after updating to v1.0.9, when you run `bard-rs` without explicitly providing a session key argument, it will attempt to retrieve the session key from the `.env` file in the following order:

1. From the path provided as an argument.
2. From the directory where the `bard-rs` binary is located.
3. From the current directory where you run the `bard-rs` command.

You can see this in action in the following screenshot:

![image](https://github.com/Alfex4936/Bard-rs/assets/2356749/e10063cf-1375-4275-8d08-5b1bb632602a)

This change gives you more flexibility in managing your session keys and makes it easier to run `bard-rs` from different locations.

Please note that for the `-p` option, which specifies where to save the chat history in markdown format, you still need to provide an explicit path. If you don't provide a path, `bard-rs` won't save the chat history. This feature can be useful if you don't want to keep a record of certain chat sessions.

We appreciate your feedback and look forward to hearing any other suggestions you might have!

**Comment by Code-acious** [comment]
I am glad that you worked hard! and it works but there's a catch

As suggested on installation instruction page!

"cargo install bard-rs" this will have bard-rs binary in /home/user/.cargo/bin directory and if I 
cd /home/user/.cargo/bin and run bard-rs its gives me the same error as earlier :-(
have a look!
1.
![Screenshot_2023-05-16_17-14-34](https://github.com/Alfex4936/Bard-rs/assets/85301801/563b6e08-9a63-426a-9f5a-4ddb7e392541)

But if I cd /home/user/Bard-rs/target/release/  and run bard-rs it runs like a charm :-) and yes i have my .env file in both /home/user/.cargo/bin & /home/user/Bard-rs/target/release
have a look
2.
![Screenshot_2023-05-16_17-17-19](https://github.com/Alfex4936/Bard-rs/assets/85301801/342948a2-9377-4e96-959e-290339e5960d)

So for my knowledge bard-rs dosen't looks for the .env file in /home/user/.cargo/bin by default which it should as we have bard-rs binary in this directory and also it makes sense because other rust builds will also be installed here.

So please a look for a solution will be appreciated as my home directory looks bloated. :-(

And also one more problem when I git pull in /home/user/Bard-rs it said already up-to-date so I removed and rebuilded the package.
here's a screenshot
3.
![Screenshot_2023-05-16_15-53-00](https://github.com/Alfex4936/Bard-rs/assets/85301801/e37e9db9-3d74-4de1-b5f6-608e1d9cc136)

for now I will add this in my bashrc file export  PATH=$HOME/Bard-rs/target/release/:$PATH
and enjoy your work!!! Cheers mate!

**Comment by Code-acious** [comment]
here is a screenshot!
![Screenshot_2023-05-16_15-53-00](https://github.com/Alfex4936/Bard-rs/assets/85301801/1a624402
![Screenshot_2023-05-16_17-14-34](https://github.com/Alfex4936/Bard-rs/assets/85301801/563b6e08-9a63-426a-9f5a-4ddb7e392541)
-606f-46da-a5ea-6e1320e6d52
![Screenshot_2023-05-16_17-17-19](https://github.com/Alfex4936/Bard-rs/assets/85301801/342948a2-9377-4e96-959e-290339e5960d)
4)

**Comment by Code-acious** [comment]
Here's something wierd I found!
 
I added this command to my bashrc file
export PATH=$HOME/Bard-rs/target/release/:$PATH
as you can see

![Screenshot_2023-05-16_17-28-58](https://github.com/Alfex4936/Bard-rs/assets/85301801/5bb2f52c-e9d1-4f51-ac9f-605230fab8d4)

this means bard-rs should work fine for every new terminal session, but no it gives that same error :-(
have a look!

![Screenshot_2023-05-16_17-31-58](https://github.com/Alfex4936/Bard-rs/assets/85301801/926af780-435e-458d-bece-ff31cdf14ee8)

but following method works fine! I don't know what's wrong as both way of launching bard-rs according to me is same, in first method we are just adding a directory to a path.
As you can see.

![Screenshot_2023-05-16_17-33-06](https://github.com/Alfex4936/Bard-rs/assets/85301801/eef7da67-265e-404f-878a-4a43d5c2c100)

Hope you will come up with a solution!
Exams are near so I may not be able to assist you but I have some suggestions for your program:-
1. Don't kill it becasue a simple bash script that contains "bard-rs -e .env -p ./" worked for me.
2. If possible add color codes for "questions asked by user" and solution provided by Bard", "YOU prompt" and "Bard bard promt".
3. A little tip would be please test your program on another machine, not on which you're developing. If you have access to one.
That's all Cheers!

**Comment by Alfex4936** [comment]
Thank you for finding errors! Even though I tried it on my EC2 (ubuntu), Zorin OS and WSL2, indeed I didn't try that global cases.

I've noticed a bug in v1.0.9 where the code doesn't accurately locate the .env file when executed from a different directory, especially during a global installation like `cargo install`.

To improve this, I've introduced a flexible sequence in v1.1.0 where the program first searches for the .env file in the current working directory. If not found, it checks the binary's directory, and finally defaults to preset values or displays an error.

Here's a sample run on my EC2 (ubuntu-22.04) after implementing these changes:

1. Install `bard-rs` using cargo.
2. Verify `bard-rs` exists in `~/.cargo/bin`.
3. Initial run causes a panic due to missing `.env`.
4. Create `.env` in `~/.cargo/bin`.
5. Run `bard-rs` in `~/.cargo/bin` - success, as it finds the `.env`.
6. Run `bard-rs` from home folder (no `.env` present) - still successful as it fetches `.env` from `~/.cargo/bin`.

Here's a snapshot:

![image](https://github.com/Alfex4936/Bard-rs/assets/2356749/b16155de-eba0-41b9-bd47-267abb90753f)

Windows performance is consistent, both with local and global .exe, provided `.env` is in the current folder.

![image](https://github.com/Alfex4936/Bard-rs/assets/2356749/82b5c42b-59bc-4d33-b99f-b5f0afbace22)

Remember to delete your release folder path line before starting.

Also, added colors as well :)

![image](https://github.com/Alfex4936/Bard-rs/assets/2356749/945f3fa1-b783-468c-bb94-be613e7e269e)

**Comment by Code-acious** [comment]
![Screenshot_2023-05-17_08-07-32](https://github.com/Alfex4936/Bard-rs/assets/85301801/64fc8837-8991-4d30-95ac-c1528fd00c62)

For me the installation process was:-
`cargo install bard-rs`
`touch .env`
`nano .env`
enter the following
SESSION_ID= (your session ID)
save and exit nano
`nano .bashrc`
add the following
`export PATH=$HOME/.cargo/bin:$PATH`  <If you don't do it, it will say bard-rs : command not found>
save and exit nano
launch it with `bard-rs`
That's it  Explore BardAI

**Comment by Greatz08** [comment]
@Code-acious  buddy thread 'main' panicked at 'SNlM0e not found', /home/hakaishin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bard-rs-1.2.2/src/main.rs:134:14   this is the error i am getting any fix for this? :-(
